package tgb.btc.rce.enums;

public enum UserState {
    BAN_UNBAN,
    USER_REFERRAL_BALANCE,
    RANK_DISCOUNT,
    DEALS_COUNT,
    WITHDRAWAL_OF_FUNDS,
    MAILING_LIST,
    ADD_CONTACT,
    CHANGE_REFERRAL_BALANCE,
    CHECK_FOR_DATE,
    DEAL_REPORTS,
    DATE_DEAL_REPORT,
    SEND_MESSAGE_CHAT_ID,
    SEND_MESSAGE_TEXT,
    PERSONAL_BUY_CHAT_ID,
    PERSONAL_SELL_CHAT_ID,
    NEW_PERSONAL_BUY,
    NEW_PERSONAL_SELL,
    USER_INFORMATION,
    REFERRAL_PERCENT,
    NEW_REFERRAL_PERCENT,
    BOT_VARIABLES,
    SHARE_REVIEW,
    CREATE_PAYMENT_TYPE
}
