package tgb.btc.rce.enums.update;

public enum CallbackQueryData {
    SHOW_WITHDRAWAL_REQUEST,
    HIDE_WITHDRAWAL,
    DELETE_WITHDRAWAL_REQUEST,
    CHANGE_RANK_DISCOUNT,
    TURN_ON_CURRENCY,
    TURN_OFF_CURRENCY,
    TURNING_RANK_DISCOUNT,
    SHOW_DEAL,
    SHOW_API_DEAL,
    DELETE_USER_DEAL,
    DELETE_DEAL_AND_BLOCK_USER,
    CONFIRM_USER_DEAL,
    AUTO_WITHDRAWAL_DEAL,
    CONFIRM_AUTO_WITHDRAWAL_DEAL,
    BITCOIN_POOL_WITHDRAWAL,
    CLEAR_POOL,
    CONFIRM_POOL_WITHDRAWAL,
    CONFIRM_CLEAR_POOL,
    ADD_TO_POOL,
    ADDITIONAL_VERIFICATION,
    REVIEW_NAVIGATION,
    PUBLISH_REVIEW,
    DELETE_REVIEW,
    DELETING_PAYMENT_TYPE,
    DELETING_PAYMENT_TYPE_REQUISITE
}
