package tgb.btc.rce.enums.update;

public enum CallbackQueryData {
    SHOW_WITHDRAWAL_REQUEST,
    HIDE_WITHDRAWAL,
    DELETE_WITHDRAWAL_REQUEST,
    CHANGE_RANK_DISCOUNT,
    TURN_ON_CURRENCY,
    TURN_OFF_CURRENCY,
    TURNING_RANK_DISCOUNT,
    SHOW_DEAL,
    SHOW_API_DEAL,
    DELETE_USER_DEAL
}
